-- ============================================================================
-- Patient Point IXR Analytics - Analytical Views
-- ============================================================================
-- Description: Creates analytical views that pre-join engagement metrics
--              with clinical outcomes for streamlined analysis by Cortex Analyst
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE SCHEMA PATIENTPOINT_DB.IXR_ANALYTICS;

-- ============================================================================
-- V_IMPACT_ANALYSIS - Core Analytical View
-- ============================================================================
-- Purpose: Pre-aggregates IXR engagement metrics to monthly level and joins
--          with patient outcomes, enabling the Cortex Analyst to answer 
--          impact questions without complex multi-hop joins.
-- ============================================================================

CREATE OR REPLACE VIEW V_IMPACT_ANALYSIS AS
WITH monthly_engagement AS (
    SELECT 
        m.PROVIDER_NPI,
        DATE_TRUNC('MONTH', m.ENGAGEMENT_DATE) AS ENGAGEMENT_MONTH,
        COUNT(*) AS TOTAL_INTERACTIONS,
        COUNT(DISTINCT m.DEVICE_ID) AS UNIQUE_DEVICES,
        AVG(m.DWELL_TIME_SEC) AS AVG_DWELL_TIME_SEC,
        AVG(m.CLICK_COUNT) AS AVG_CLICK_COUNT,
        AVG(m.SCROLL_DEPTH_PCT) AS AVG_SCROLL_DEPTH_PCT,
        MAX(m.SCROLL_DEPTH_PCT) AS MAX_SCROLL_DEPTH_PCT,
        SUM(m.DWELL_TIME_SEC) AS TOTAL_DWELL_TIME_SEC,
        SUM(m.CLICK_COUNT) AS TOTAL_CLICKS,
        -- Engagement score: weighted composite metric
        (AVG(m.SCROLL_DEPTH_PCT) * 0.4 + 
         AVG(m.CLICK_COUNT) * 2.0 + 
         AVG(m.DWELL_TIME_SEC) * 0.1) AS ENGAGEMENT_SCORE,
        -- Content category breakdown
        MAX(CASE WHEN m.CONTENT_CATEGORY = 'Vaccinations' THEN 1 ELSE 0 END) AS HAS_VACCINATION_CONTENT,
        MAX(CASE WHEN m.CONTENT_CATEGORY = 'Cancer Screening' THEN 1 ELSE 0 END) AS HAS_SCREENING_CONTENT,
        MAX(CASE WHEN m.CONTENT_CATEGORY = 'Appointment Reminders' THEN 1 ELSE 0 END) AS HAS_APPOINTMENT_CONTENT
    FROM IXR_METRICS m
    GROUP BY m.PROVIDER_NPI, ENGAGEMENT_MONTH
)
SELECT 
    -- Provider Information
    p.NPI AS PROVIDER_NPI,
    p.PROVIDER_NAME,
    p.SPECIALTY,
    p.REGION,
    p.IS_ACTIVE AS PROVIDER_IS_ACTIVE,
    
    -- Time Period
    o.OUTCOME_MONTH,
    YEAR(o.OUTCOME_MONTH) AS OUTCOME_YEAR,
    MONTHNAME(o.OUTCOME_MONTH) AS OUTCOME_MONTH_NAME,
    QUARTER(o.OUTCOME_MONTH) AS OUTCOME_QUARTER,
    
    -- Engagement Metrics (Monthly Averages)
    COALESCE(e.TOTAL_INTERACTIONS, 0) AS TOTAL_INTERACTIONS,
    COALESCE(e.UNIQUE_DEVICES, 0) AS UNIQUE_DEVICES,
    COALESCE(ROUND(e.AVG_DWELL_TIME_SEC, 2), 0) AS AVG_DWELL_TIME_SEC,
    COALESCE(ROUND(e.AVG_CLICK_COUNT, 2), 0) AS AVG_CLICK_COUNT,
    COALESCE(ROUND(e.AVG_SCROLL_DEPTH_PCT, 2), 0) AS AVG_SCROLL_DEPTH_PCT,
    COALESCE(e.MAX_SCROLL_DEPTH_PCT, 0) AS MAX_SCROLL_DEPTH_PCT,
    COALESCE(e.TOTAL_DWELL_TIME_SEC, 0) AS TOTAL_DWELL_TIME_SEC,
    COALESCE(e.TOTAL_CLICKS, 0) AS TOTAL_CLICKS,
    COALESCE(ROUND(e.ENGAGEMENT_SCORE, 2), 0) AS ENGAGEMENT_SCORE,
    
    -- Engagement Level Classification
    CASE 
        WHEN COALESCE(e.AVG_SCROLL_DEPTH_PCT, 0) > 70 AND COALESCE(e.AVG_CLICK_COUNT, 0) > 10 THEN 'High'
        WHEN COALESCE(e.AVG_SCROLL_DEPTH_PCT, 0) > 40 AND COALESCE(e.AVG_CLICK_COUNT, 0) > 5 THEN 'Medium'
        ELSE 'Low'
    END AS ENGAGEMENT_LEVEL,
    
    -- Content Flags
    COALESCE(e.HAS_VACCINATION_CONTENT, 0) AS HAS_VACCINATION_CONTENT,
    COALESCE(e.HAS_SCREENING_CONTENT, 0) AS HAS_SCREENING_CONTENT,
    COALESCE(e.HAS_APPOINTMENT_CONTENT, 0) AS HAS_APPOINTMENT_CONTENT,
    
    -- Clinical Outcomes
    o.VACCINES_ADMINISTERED,
    o.SCREENINGS_COMPLETED,
    o.APPOINTMENT_SHOW_RATE,
    
    -- Derived Metrics for Analysis
    CASE 
        WHEN COALESCE(e.TOTAL_INTERACTIONS, 0) > 0 THEN 
            ROUND(o.VACCINES_ADMINISTERED / e.TOTAL_INTERACTIONS::FLOAT, 4)
        ELSE 0 
    END AS VACCINES_PER_INTERACTION,
    
    CASE 
        WHEN COALESCE(e.TOTAL_INTERACTIONS, 0) > 0 THEN 
            ROUND(o.SCREENINGS_COMPLETED / e.TOTAL_INTERACTIONS::FLOAT, 4)
        ELSE 0 
    END AS SCREENINGS_PER_INTERACTION

FROM PROVIDER_DIM p
CROSS JOIN (
    SELECT DISTINCT OUTCOME_MONTH 
    FROM PATIENT_OUTCOMES
) o
LEFT JOIN monthly_engagement e 
    ON p.NPI = e.PROVIDER_NPI 
    AND o.OUTCOME_MONTH = e.ENGAGEMENT_MONTH
LEFT JOIN PATIENT_OUTCOMES o 
    ON p.NPI = o.PROVIDER_NPI 
    AND o.OUTCOME_MONTH = o.OUTCOME_MONTH
WHERE o.OUTCOME_MONTH IS NOT NULL;

-- ============================================================================
-- Additional Supporting Views
-- ============================================================================

-- Provider Summary View - High-level provider metrics
CREATE OR REPLACE VIEW V_PROVIDER_SUMMARY AS
SELECT 
    PROVIDER_NPI,
    PROVIDER_NAME,
    SPECIALTY,
    REGION,
    PROVIDER_IS_ACTIVE,
    COUNT(DISTINCT OUTCOME_MONTH) AS MONTHS_ACTIVE,
    ROUND(AVG(AVG_SCROLL_DEPTH_PCT), 2) AS OVERALL_AVG_SCROLL_DEPTH,
    ROUND(AVG(AVG_CLICK_COUNT), 2) AS OVERALL_AVG_CLICK_COUNT,
    ROUND(AVG(AVG_DWELL_TIME_SEC), 2) AS OVERALL_AVG_DWELL_TIME,
    SUM(VACCINES_ADMINISTERED) AS TOTAL_VACCINES_ADMINISTERED,
    SUM(SCREENINGS_COMPLETED) AS TOTAL_SCREENINGS_COMPLETED,
    ROUND(AVG(APPOINTMENT_SHOW_RATE), 3) AS AVG_APPOINTMENT_SHOW_RATE,
    MAX(ENGAGEMENT_LEVEL) AS PRIMARY_ENGAGEMENT_LEVEL
FROM V_IMPACT_ANALYSIS
GROUP BY 
    PROVIDER_NPI,
    PROVIDER_NAME,
    SPECIALTY,
    REGION,
    PROVIDER_IS_ACTIVE;

-- Content Performance View - Which content drives outcomes
CREATE OR REPLACE VIEW V_CONTENT_PERFORMANCE AS
SELECT 
    m.CONTENT_CATEGORY,
    COUNT(DISTINCT m.PROVIDER_NPI) AS PROVIDERS_ENGAGED,
    COUNT(*) AS TOTAL_VIEWS,
    ROUND(AVG(m.DWELL_TIME_SEC), 2) AS AVG_DWELL_TIME_SEC,
    ROUND(AVG(m.CLICK_COUNT), 2) AS AVG_CLICK_COUNT,
    ROUND(AVG(m.SCROLL_DEPTH_PCT), 2) AS AVG_SCROLL_DEPTH_PCT,
    -- Correlate with outcomes
    ROUND(AVG(o.VACCINES_ADMINISTERED), 2) AS AVG_VACCINES_FOR_PROVIDERS,
    ROUND(AVG(o.SCREENINGS_COMPLETED), 2) AS AVG_SCREENINGS_FOR_PROVIDERS,
    ROUND(AVG(o.APPOINTMENT_SHOW_RATE), 3) AS AVG_SHOW_RATE_FOR_PROVIDERS
FROM IXR_METRICS m
LEFT JOIN PATIENT_OUTCOMES o 
    ON m.PROVIDER_NPI = o.PROVIDER_NPI 
    AND DATE_TRUNC('MONTH', m.ENGAGEMENT_DATE) = o.OUTCOME_MONTH
GROUP BY m.CONTENT_CATEGORY
ORDER BY AVG_SCROLL_DEPTH_PCT DESC;

-- Monthly Trend View - Time series analysis
CREATE OR REPLACE VIEW V_MONTHLY_TRENDS AS
SELECT 
    OUTCOME_MONTH,
    OUTCOME_YEAR,
    OUTCOME_MONTH_NAME,
    OUTCOME_QUARTER,
    COUNT(DISTINCT PROVIDER_NPI) AS ACTIVE_PROVIDERS,
    SUM(TOTAL_INTERACTIONS) AS TOTAL_INTERACTIONS,
    ROUND(AVG(AVG_SCROLL_DEPTH_PCT), 2) AS AVG_SCROLL_DEPTH_PCT,
    ROUND(AVG(AVG_CLICK_COUNT), 2) AS AVG_CLICK_COUNT,
    ROUND(AVG(AVG_DWELL_TIME_SEC), 2) AS AVG_DWELL_TIME_SEC,
    SUM(VACCINES_ADMINISTERED) AS TOTAL_VACCINES_ADMINISTERED,
    SUM(SCREENINGS_COMPLETED) AS TOTAL_SCREENINGS_COMPLETED,
    ROUND(AVG(APPOINTMENT_SHOW_RATE), 3) AS AVG_APPOINTMENT_SHOW_RATE,
    -- Month-over-month growth
    ROUND(
        (SUM(VACCINES_ADMINISTERED) - LAG(SUM(VACCINES_ADMINISTERED)) OVER (ORDER BY OUTCOME_MONTH)) 
        / NULLIF(LAG(SUM(VACCINES_ADMINISTERED)) OVER (ORDER BY OUTCOME_MONTH), 0) * 100, 
        2
    ) AS VACCINES_MOM_GROWTH_PCT
FROM V_IMPACT_ANALYSIS
GROUP BY 
    OUTCOME_MONTH,
    OUTCOME_YEAR,
    OUTCOME_MONTH_NAME,
    OUTCOME_QUARTER
ORDER BY OUTCOME_MONTH;

-- Specialty Comparison View
CREATE OR REPLACE VIEW V_SPECIALTY_COMPARISON AS
SELECT 
    SPECIALTY,
    COUNT(DISTINCT PROVIDER_NPI) AS PROVIDER_COUNT,
    ROUND(AVG(AVG_SCROLL_DEPTH_PCT), 2) AS AVG_SCROLL_DEPTH_PCT,
    ROUND(AVG(AVG_CLICK_COUNT), 2) AS AVG_CLICK_COUNT,
    SUM(VACCINES_ADMINISTERED) AS TOTAL_VACCINES,
    SUM(SCREENINGS_COMPLETED) AS TOTAL_SCREENINGS,
    ROUND(AVG(APPOINTMENT_SHOW_RATE), 3) AS AVG_SHOW_RATE,
    SUM(CASE WHEN PROVIDER_IS_ACTIVE = TRUE THEN 1 ELSE 0 END) AS ACTIVE_PROVIDERS,
    ROUND(
        SUM(CASE WHEN PROVIDER_IS_ACTIVE = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(DISTINCT PROVIDER_NPI),
        2
    ) AS RETENTION_RATE_PCT
FROM V_IMPACT_ANALYSIS
GROUP BY SPECIALTY
ORDER BY TOTAL_VACCINES DESC;

-- ============================================================================
-- Verification Queries
-- ============================================================================

-- Sample data from main analytical view
SELECT * 
FROM V_IMPACT_ANALYSIS 
WHERE ENGAGEMENT_LEVEL = 'High'
LIMIT 5;

-- Show correlation summary
SELECT 
    ENGAGEMENT_LEVEL,
    COUNT(*) AS RECORD_COUNT,
    ROUND(AVG(AVG_SCROLL_DEPTH_PCT), 2) AS AVG_SCROLL,
    ROUND(AVG(AVG_CLICK_COUNT), 2) AS AVG_CLICKS,
    ROUND(AVG(VACCINES_ADMINISTERED), 2) AS AVG_VACCINES,
    ROUND(AVG(SCREENINGS_COMPLETED), 2) AS AVG_SCREENINGS,
    ROUND(AVG(APPOINTMENT_SHOW_RATE), 3) AS AVG_SHOW_RATE
FROM V_IMPACT_ANALYSIS
GROUP BY ENGAGEMENT_LEVEL
ORDER BY 
    CASE ENGAGEMENT_LEVEL 
        WHEN 'High' THEN 1 
        WHEN 'Medium' THEN 2 
        ELSE 3 
    END;

-- View counts
SELECT 
    'V_IMPACT_ANALYSIS' AS VIEW_NAME, 
    COUNT(*) AS ROW_COUNT 
FROM V_IMPACT_ANALYSIS
UNION ALL
SELECT 
    'V_PROVIDER_SUMMARY', 
    COUNT(*) 
FROM V_PROVIDER_SUMMARY
UNION ALL
SELECT 
    'V_CONTENT_PERFORMANCE', 
    COUNT(*) 
FROM V_CONTENT_PERFORMANCE
UNION ALL
SELECT 
    'V_MONTHLY_TRENDS', 
    COUNT(*) 
FROM V_MONTHLY_TRENDS
UNION ALL
SELECT 
    'V_SPECIALTY_COMPARISON', 
    COUNT(*) 
FROM V_SPECIALTY_COMPARISON;

SELECT '✓ Analytical views created successfully.' AS STATUS;

